CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE CLIENTE (
	ID_CLIENTE INT PRIMARY KEY,
	NOME VARCHAR(50),
	LIMITE_CREDITO DECIMAL(10,2) );
    
INSERT INTO CLIENTE VALUES (1, "VALTER", 5000),
                           (2, "MARIA", 7000);    

 CREATE TABLE VENDA (
	ID_VENDA INT PRIMARY KEY,
	ID_CLIENTE INT,
	DT_VENDA DATE,
	VALOR DECIMAL(10,2),
  FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) );


CREATE TABLE PAGAMENTO (
	ID_PAGAMENTO INT PRIMARY KEY,
	ID_VENDA INT,
	NR_PARCELA INT,
	DT_VENCIMENTO DATE,
	DT_PAGAMENTO DATE,
	VALOR_PRINCIPAL DECIMAL(10,2),
	VALOR_JUROS DECIMAL(10,2),
	VALOR_PAGAMENTO DECIMAL(10,2),
  FOREIGN KEY(ID_VENDA) REFERENCES VENDA(ID_VENDA));
    

# Trigger para debitar o limite de crédito do cliente após ser inserido uma venda deste cliente.
DELIMITER $$
CREATE TRIGGER DEB_LIM_CLIENTE
AFTER INSERT ON VENDA
FOR EACH ROW
BEGIN
	UPDATE CLIENTE 
	SET LIMITE_CREDITO = LIMITE_CREDITO - NEW.VALOR
        WHERE ID_CLIENTE = NEW.ID_CLIENTE;
END 
$$ DELIMITER ;

# Trigger para creditar o limite de crédito do cliente após ser inserido um pagamento de uma venda deste cliente.
DELIMITER $$  
CREATE TRIGGER TGR_CREDITAR_LIM 
AFTER INSERT ON PAGAMENTO
FOR EACH ROW  
BEGIN 
	UPDATE CLIENTE
		SET LIMITE_CREDITO = LIMITE_CREDITO + NEW.VALOR_PAGAMENTO
			WHERE ID_CLIENTE = ( SELECT DISTINCT ID_CLIENTE FROM VENDA V, PAGAMENTO P WHERE V.ID_VENDA = P.ID_VENDA);
END
$$ DELIMITER ;

# TESTE
DESC VENDA;
DESC PAGAMENTO;
SELECT * FROM CLIENTE;
SELECT * FROM VENDA;
SELECT * FROM PAGAMENTO;
INSERT INTO VENDA VALUES (1004, 2, '2022-10-20', 500);
INSERT INTO PAGAMENTO VALUES (10008, 1004, 2, '2022-10-20', '2022-10-20', 500, 0, 500);
