# Crie uma função que some todos os clientes cadastrados em uma loja durante um dia.
DELIMITER $$
CREATE FUNCTION FN_SOMA_CLIENTE()
RETURNS DECIMAL(10,2)
CONTAINS SQL
BEGIN
	DECLARE VALOR_FINAL DECIMAL(10,2);
  SET VALOR_FINAL = (
    SELECT SUM(SALDO_CLIENTE) AS TOTAL 
    FROM CLIENTES 
    GROUP BY STATUS 
    HAVING STATUS = TRUE;
  ) 
  RETURN VALOR_FINAL;
END
$$ DELIMITER ;
